const regras = (prefix, nomd) => { 
	return `
 *REGRAS DO 𝕺𝖑𝖆𝖋 𝕭𝖔𝖙*
 
 *É NECESSÁRIO TER 20 MEMBROS NO GP*
 *OS ADM DO GP TEM QUE AJUDA O DONO*
 *TEM QUE BAIXA O KWAI E POR MEU CÓDIGO*
 *APÓS FAZER ISSO SEU GP ESTÁ LIBERADO PRO USO DO BOT*
 *SE NÃO FAZER ISSO NÃO VAI TER ACESSO AO BOT*
 *ESSE BOT É PÚBLICO GERAL PODE USAR MAIS CLARO COM SUAS REGRAS*
 *MANDA O PRINT NO PV DO MEU DONO REFERENTE AO CÓDIGO DO KWAI*
 *É SIMPLES ESSA REGRA APROVEITE O BOT CHEIO DE NOVIDADES*
 *ISSO DÁ MUITO TRABALHO ENTÃO NN VOU FICA SEM RECEBER ND EM TROCA*
 
 *CÓDIGO KWAI:* ~Kwai223676707~
 
 *NÚMERO DONO PRA PRINT:* *_wa.me/5577991174304_*
 
 
 *OBG 𝕺𝖑𝖆𝖋 𝕭𝖔𝖙*
 
 *⤵️COMANDOS⤵️*
 
 *.help1*`
}

exports.regras = regras



